GET http://localhost:3000/

###
POST http://localhost:3000/user/signUp
Content-Type: application/json

{
    "name": "Rayen",
    "lastName":"Harhouri",
    "email":"rayenharhouri99@gmail.com",
    "password":"123",
    "adress":"Mnihla",
    "driverLicense":"147852369",
    "delevredOn": "2020-03-09",
    "number": 12345678
}
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email" : "rayenharhouri99@gmail.com",
    "password" : "123"
}
###
PATCH http://localhost:3000/user/updateUser
Content-Type: application/json

{
    "driverLicence" : "F23322443",
    "name" : "mezen"
}
###
POST http://localhost:3000/user/forgotPassword
Content-Type: application/json

{
    
    "email" : "rayenharhouri99@gmail.com"
}





###
POST http://localhost:3000/user/send-confirmation-email
Content-Type: application/json

{
    "email" : "rayenharhouri99@gmail.com"
}

###
POST http://localhost:3000/user/forgotPassword
Content-Type: application/json

{
    "email" : "rayenharhouri99@gmail.com"
}

###
POST http://localhost:3000/user/confirmationOtp
Content-Type: application/json

{
    "otp" : "2103"
}

###
PUT http://localhost:3000/user/updatePassword
Content-Type: application/json

{
    "email" : "rayenharhouri99@gmail.com",
    "newPassword" : "rayen123",
    "newPasswordConfirm" : "rayen123"
}
###
POST http://localhost:3000/user/userProfil
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNzc5ZGJlZDkxZGE2NGIxZDhmYjRkYSIsIm5hbWUiOiJyYXllbiIsImxhc3ROYW1lIjoiaHJhcmgiLCJhZHJlc3MiOiJhemVhemVheiIsImRyaXZlckxpY2Vuc2UiOiIxMjM1NjQiLCJkZWxldnJlZE9uIjoiMjAyMi0xMS0xOFQxNDo1ODo0OC4wMDBaIiwibnVtYmVyIjo3NDU4LCJwYXNzd29yZCI6IiQyYiQxMCRERk1oektLRVNONjg3RHF4V0laWncuSlliSGpZUjlCTkdRMVpZUEZUNTZ6ZkloS3NoOG0vdSIsImVtYWlsIjoicmF5ZW5oYXJob3VyaTk5QGdtYWlsLmNvbSIsInZlcmlmaWVkIjp0cnVlLCJvdHAiOjg5ODksImNyZWF0ZWRBdCI6IjIwMjItMTEtMThUMTQ6NTk6MTAuNTIyWiIsInVwZGF0ZWRBdCI6IjIwMjItMTEtMThUMTQ6NTk6MzguMTE0WiIsIl9fdiI6MH0sImlhdCI6MTY2ODc4NDY4NiwiZXhwIjoxNjY4Nzg4Mjg2fQ.gMyuGlXUO5lkgTvUBGYEXvX_ThOv_AL4M3Wj9-8nKuA"
}

###
GET  http://localhost:3000/user/confirmation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNzc5ZGJlZDkxZGE2NGIxZDhmYjRkYSIsIm5hbWUiOiJyYXllbiIsImxhc3ROYW1lIjoiaHJhcmgiLCJhZHJlc3MiOiJhemVhemVheiIsImRyaXZlckxpY2Vuc2UiOiIxMjM1NjQiLCJkZWxldnJlZE9uIjoiMjAyMi0xMS0xOFQxNDo1ODo0OC4wMDBaIiwibnVtYmVyIjo3NDU4LCJwYXNzd29yZCI6IiQyYiQxMCRERk1oektLRVNONjg3RHF4V0laWncuSlliSGpZUjlCTkdRMVpZUEZUNTZ6ZkloS3NoOG0vdSIsImVtYWlsIjoicmF5ZW5oYXJob3VyaTk5QGdtYWlsLmNvbSIsInZlcmlmaWVkIjpmYWxzZSwib3RwIjo4OTg5LCJjcmVhdGVkQXQiOiIyMDIyLTExLTE4VDE0OjU5OjEwLjUyMloiLCJ1cGRhdGVkQXQiOiIyMDIyLTExLTE4VDE0OjU5OjEwLjUyMloiLCJfX3YiOjB9LCJpYXQiOjE2Njg3ODM1NjAsImV4cCI6MTY2ODc4NzE2MH0.X6h4H4MtsCFIq9XNuI47ItiYMn_qWv1rN5a3wDHDuXU
Content-Type: application/json




###
GET http://localhost:3000/img/Audi.png

###
POST http://localhost:3000/car/addNew
Content-Type: application/json

{
    "brand" : "BMW",
    "type" : "naarash",
    "numSerie" : "123456278922322",
    "fiscalPower" : 7,
    "numImmatriculation" : "123 TUN 4015",
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzN2UzZmQ3Y2I2Njk3ZWRhNGIzZTA0NSIsIm5hbWUiOiJSYXllbiIsImxhc3ROYW1lIjoiSGFyaG91cmkiLCJhZHJlc3MiOiJNbmlobGEiLCJkcml2ZXJMaWNlbnNlIjoiMTQ3ODUyMzY5IiwiZGVsZXZyZWRPbiI6IjIwMjAtMDMtMDlUMDA6MDA6MDAuMDAwWiIsIm51bWJlciI6MTIzNDU2NzgsInBhc3N3b3JkIjoiJDJiJDEwJFZ5cTVmOUFZTVJLYnN2dXFvYlNzNXU4dXNZNFpQeEQuUHVhVlJxamRBOGo1VTF2dU9Xa0JpIiwiZW1haWwiOiJyYXllbmhhcmhvdXJpOTlAZ21haWwuY29tIiwidmVyaWZpZWQiOmZhbHNlLCJvdHAiOjg5ODksImNhcnMiOltdLCJjcmVhdGVkQXQiOiIyMDIyLTExLTIzVDE1OjQ0OjIzLjU5NloiLCJ1cGRhdGVkQXQiOiIyMDIyLTExLTIzVDE1OjQ0OjIzLjU5NloiLCJfX3YiOjB9LCJpYXQiOjE2NjkyMTgyOTAsImV4cCI6MTY2OTIyMTg5MH0.k1_WCT_i7MMi6gH4wplYfo2AVugaivu77zdLqEY1_dM"
}

###
DELETE http://localhost:3000/car/removeCar
Content-Type: application/json

{
    "numSerie" : "123456789"
}

###
GET http://localhost:3000/car/getCar
Content-Type: application/json

{
    "numSerie" : "12345678922322"
}
### 
GET http://localhost:3000/car/allCars
Content-Type: application/json



