GET http://localhost:3000/

###
POST http://localhost:3000/user/signUp
Content-Type: application/json

{
    "name": "Rayen",
    "lastName":"Harhouri",
    "email":"rayenharhouri99@gmail.com",
    "password":"rayen123",
    "adress":"Mnihla",
    "driverLicense":"147852369",
    "delevredOn": "2020-03-09",
    "number": 12345678
}
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email" : "rayenharhouri99@gmail.com",
    "password" : "something"
}
###
PATCH http://localhost:3000/user/updateUser
Content-Type: application/json

{
    "driverLicence" : "something",
    "name" : "Rayen"
}
###
POST http://localhost:3000/user/forgetPassword
Content-Type: application/json

{
    
    "email" : "rayen@rayen.com"
}





###
POST http://localhost:3000/user/send-confirmation-email
Content-Type: application/json

{
    "email" : "rayenharhouri99@gmail.com"
}

###
POST http://localhost:3000/user/forgotPassword
Content-Type: application/json

{
    "email" : "rayenharhouri99@gmail.com"
}

###
POST http://localhost:3000/user/confirmationOtp
Content-Type: application/json

{
    "otp" : "2103"
}